<a href="https://colab.research.google.com/github/Rafterbang/Mobile6/blob/master/Modul%201%20PD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Kegiatan Modul 1**

**Poin penilaian :**

* Tingkat kesesuaian output program
* Kerapian kode program
* Kesederhanaan Kode

Kegiatan 1 : **15 poin**

Terdapat suatu list seperti berikut : `a=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. Buatlah program untuk mencari suatu angka dalam list.

```
Cari : 5
Output : 5 found at index 4
```

In [75]:
# TULIS CODE ANDA DISINI

def cari(listData, data):
  i=0
  ketemu = False
  while i < len(listData) and not ketemu:
    if a[i]==data:
      ketemu=True
      print(data, "found at index", a.index(data))
    else:
      i = i+1
  return ketemu

a = [1,2,3,4,5,6,7,8,9,10]
cari(a,5)

5 found at index 4


True

Kegiatan 2 : **15 poin**

Tulis program Python untuk menghapus tupel kosong dari daftar list tupel dibawah.

In [76]:
L = [('informatika', 'umm'), (), (), ('praktikum', 'data', 'mining'), ('Berhasil')]

```
# Output : [('informatika', 'umm'), ('praktikum', 'data', 'mining'), 'Berhasil']
```



In [77]:
# TULIS CODE ANDA DISINI
del (L[1:3])
print(L)

[('informatika', 'umm'), ('praktikum', 'data', 'mining'), 'Berhasil']


Kegiatan 3 : **15 poin**

Urutkan daftar tuple dibawah ini berdasarkan nilai **desimalnya** dari kecil ke besar.

In [25]:
times = [('Isya', '19.10'), ('Dzuhur', '12.20'), ('Tidur', '23.00'), ('Ashar', '15.10'), ('Magrib', '17.40')]

```
# Output : [('Dzuhur', '12.20'), ('Ashar', '15.10'), ('Magrib', '17.40'), ('Isya', '19.10'), ('Tidur', '24.5')]
```



In [26]:
# TULIS CODE ANDA DISINI
sort = sorted(times, key=lambda x: x[1])
print (sort)

[('Dzuhur', '12.20'), ('Ashar', '15.10'), ('Magrib', '17.40'), ('Isya', '19.10'), ('Tidur', '23.00')]


Kegiatan 4 : **10 poin**

Tulis program Python untuk menghapus elemen bernilai duplikat dari list.

In [63]:
a = [10,20,30,20,10,50,60,40,80,50,40]

```
# Output : a = [10, 20, 30, 50, 60, 40, 80]
```



In [66]:
# TULIS CODE ANDA DISINI
a = list(dict.fromkeys(a))
print("a =",a)

a = [10, 20, 30, 50, 60, 40, 80]


Kegiatan 5 : **15 poin**

Buat program untuk mengkonversi numpy array menjadi list dan tuple. Gunakan keyword `type(varName)` untuk mengetahui jenis atau tipe data dari variabel atau nilai. 

In [39]:
# TULIS CODE ANDA DISINI
import numpy as np
a = np.array ([5,4,3,2,1])
b = (list(a))
c = (tuple(a))
print("Numpy :",a, type(a))
print("List :",b, type(b))
print("Tuple :",c, type(c))

#type(a), type(b), type(c)

Numpy : [5 4 3 2 1] <class 'numpy.ndarray'>
List : [5, 4, 3, 2, 1] <class 'list'>
Tuple : (5, 4, 3, 2, 1) <class 'tuple'>


Kegiatan 6 : **10 poin**

Tulis program untuk menghitung jarak Euclidean dari p1 dan p2. Anda dibebaskan disini, sehingga anda dapat menggunakan library apapun dan teknik apapun.

**Note :**
Dalam matematika, jarak Euclidean atau metrik Euclidean adalah jarak garis lurus **"ordinary"** antara dua titik dalam ruang Euclidean. Dengan jarak ini, ruang Euclidean menjadi ruang metrik. Norma terkait disebut norma Euclidean. Literatur yang lebih lama menyebut metrik sebagai metrik Pythagoras

**Read More :** 
*   [Euclidean Distance](http://rosalind.info/glossary/euclidean-distance/)
*   [Python Math](https://docs.python.org/3/library/math.html)
*   [Scipy](https://docs.scipy.org/doc/scipy/reference/)
*   [Numpy](https://numpy.org/doc/stable/)



In [ ]:
p1 = (1, 2, 3)
p2 = (4, 5, 6)

```
# Output
Euclidean distance:  5.196152422706632
```


In [41]:
# TULIS CODE ANDA DISINI
import numpy as np 
#Merubah tuple menjadi numpy terlebih dahulu
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])

jarak = np.linalg.norm(p1-p2)

print("Euclidean distance: ",jarak)

Euclidean distance:  5.196152422706632


Kegiatan 7 : **20 poin**

Tulis program NumPy untuk menghitung frekuensi keluarnya nilai di dalam array numpy berikut.

In [42]:
import numpy as np
a = np.array( [40,20,10,30,20,40,30,10,20,50,10,40] )

```
# Output
Jumlah nilai unik dari array:
[[10 20 30 40 50]
 [ 3  3  2  3  1]]
```


In [46]:
# TULIS CODE ANDA DISINI
unik, hitung = np.unique(a, return_counts=True)

print ("Jumlah nilai unik dari array: \n",np.asarray((unik, hitung)))

Jumlah nilai unik dari array: 
 [[10 20 30 40 50]
 [ 3  3  2  3  1]]
